[project]
name = "test-lighton-ocr-1b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.1",
    "pillow>=12.1.0",
    "pypdfium2>=5.3.0",
    "requests>=2.32.5",
]
